services:
  svelte-site:
    build: .
    container_name: bullying-project
    ports:
      - "80:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    security_opt:
      - no-new-privileges:true
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0